opt_in_rules:
  - attributes
  - closure_end_indentation
  - closure_spacing
  - empty_count
  - explicit_init
  - first_where
  - nimble_operator
  - number_separator
  - overridden_super_call
  - operator_usage_whitespace
  - object_literal
  - prohibited_super_call
  - redundant_nil_coalescing

disabled_rules:
  - multiple_closures_with_trailing_closure

line_length:
  warning: 200
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true

identifier_name:
  excluded:
    - id
    - to
    - _placeholder
